/**
 * Standard event types used across all agents
 */

export const EventTypes = {
  // Code generation events
  CODE_GENERATED: 'CODE_GENERATED',
  CODE_UPDATED: 'CODE_UPDATED',
  CODE_DELETED: 'CODE_DELETED',

  // Code analysis events
  CODE_ANALYZED: 'CODE_ANALYZED',
  QUALITY_SCORED: 'QUALITY_SCORED',
  ISSUE_DETECTED: 'ISSUE_DETECTED',

  // Testing events
  TESTS_STARTED: 'TESTS_STARTED',
  TESTS_COMPLETED: 'TESTS_COMPLETED',
  TESTS_FAILED: 'TESTS_FAILED',
  TESTS_GENERATED: 'TESTS_GENERATED',
  COVERAGE_UPDATED: 'COVERAGE_UPDATED',

  // Build & deployment events
  BUILD_STARTED: 'BUILD_STARTED',
  BUILD_COMPLETED: 'BUILD_COMPLETED',
  BUILD_FAILED: 'BUILD_FAILED',
  DEPLOYMENT_STARTED: 'DEPLOYMENT_STARTED',
  DEPLOYMENT_COMPLETED: 'DEPLOYMENT_COMPLETED',

  // PR & Git events
  PR_CREATED: 'PR_CREATED',
  PR_UPDATED: 'PR_UPDATED',
  PR_MERGED: 'PR_MERGED',
  PR_CLOSED: 'PR_CLOSED',

  // Documentation events
  DOCS_UPDATED: 'DOCS_UPDATED',
  DOCS_SYNCED: 'DOCS_SYNCED',

  // Error & recovery events
  ERROR_OCCURRED: 'ERROR_OCCURRED',
  ROLLBACK_REQUESTED: 'ROLLBACK_REQUESTED',
  ROLLBACK_COMPLETED: 'ROLLBACK_COMPLETED',

  // Agent lifecycle events
  AGENT_STARTED: 'AGENT_STARTED',
  AGENT_COMPLETED: 'AGENT_COMPLETED',
  AGENT_FAILED: 'AGENT_FAILED',
  AGENT_HEALTH_CHECK: 'AGENT_HEALTH_CHECK',

  // Metrics events
  METRICS_COLLECTED: 'METRICS_COLLECTED',
  ALERT_TRIGGERED: 'ALERT_TRIGGERED',

  // Change detection events
  CHANGE_DETECTED: 'CHANGE_DETECTED',

  // Auto-fix events (for agent coordination)
  AUTO_FIX_REQUESTED: 'AUTO_FIX_REQUESTED',
  FIX_COMPLETED: 'FIX_COMPLETED',
  FIX_FAILED: 'FIX_FAILED',

  // Code review events
  REVIEW_REQUESTED: 'REVIEW_REQUESTED',
  REVIEW_COMPLETED: 'REVIEW_COMPLETED',

  // Security scan events
  SECURITY_SCAN_REQUESTED: 'SECURITY_SCAN_REQUESTED',
  SECURITY_SCAN_COMPLETED: 'SECURITY_SCAN_COMPLETED',

  // Dependency analysis events
  ANALYZE_DEPENDENCIES: 'ANALYZE_DEPENDENCIES',
  DEPENDENCIES_ANALYZED: 'DEPENDENCIES_ANALYZED',
  UPDATE_DEPENDENCIES: 'UPDATE_DEPENDENCIES',
  DEPENDENCIES_UPDATED: 'DEPENDENCIES_UPDATED',

  // Test generation events
  GENERATE_TESTS: 'GENERATE_TESTS',

  // Skill lifecycle events
  SKILL_READY: 'SKILL_READY'
};

export default EventTypes;
