/**
 * Minions Project Schema Index
 * ============================
 * Central registry for all project file schemas.
 *
 * Schema Ownership:
 * - Nefario (Planner): scope.json, requirements.json
 * - Silas (ProjectManager): project.json, state.json
 * - Tom (SecurityRisk): risks.json, security/*, ops/*
 * - Lucy (ProjectCompletion): gaps.json, quality/*
 */

import scopeSchema from './scope.schema.json' assert { type: 'json' };
import requirementsSchema from './requirements.schema.json' assert { type: 'json' };
import assumptionsSchema from './assumptions.schema.json' assert { type: 'json' };
import risksSchema from './risks.schema.json' assert { type: 'json' };
import threatModelSchema from './threat-model.schema.json' assert { type: 'json' };
import permissionsSchema from './permissions.schema.json' assert { type: 'json' };
import environmentsSchema from './environments.schema.json' assert { type: 'json' };
import auditLogSchema from './audit-log.schema.json' assert { type: 'json' };
import gapsSchema from './gaps.schema.json' assert { type: 'json' };

/**
 * Schema registry with ownership information
 */
export const schemas = {
  // Nefario's files
  'scope.json': {
    schema: scopeSchema,
    owner: 'Nefario',
    location: 'scope.json',
    description: 'Project scope and boundaries'
  },
  'requirements.json': {
    schema: requirementsSchema,
    owner: 'Nefario',
    location: 'requirements.json',
    description: 'Functional and non-functional requirements'
  },

  // Shared/General files
  'assumptions.json': {
    schema: assumptionsSchema,
    owner: null, // Multiple agents can update
    location: 'assumptions.json',
    description: 'Project assumptions'
  },

  // Tom's files
  'risks.json': {
    schema: risksSchema,
    owner: 'Tom',
    location: 'risks.json',
    description: 'Project risk register'
  },
  'threat-model.json': {
    schema: threatModelSchema,
    owner: 'Tom',
    location: 'security/threat-model.json',
    description: 'STRIDE threat model'
  },
  'permissions.json': {
    schema: permissionsSchema,
    owner: 'Tom',
    location: 'security/permissions.json',
    description: 'RBAC configuration'
  },
  'environments.json': {
    schema: environmentsSchema,
    owner: 'Tom',
    location: 'ops/environments.json',
    description: 'Environment configurations'
  },
  'audit-log.json': {
    schema: auditLogSchema,
    owner: 'Tom',
    location: 'security/audit-log.json',
    description: 'Security audit trail'
  },

  // Lucy's files
  'gaps.json': {
    schema: gapsSchema,
    owner: 'Lucy',
    location: 'gaps.json',
    description: 'Gap analysis and tracking'
  }
};

/**
 * Get schema by file name
 */
export function getSchema(fileName) {
  return schemas[fileName]?.schema || null;
}

/**
 * Get owner of a file
 */
export function getOwner(fileName) {
  return schemas[fileName]?.owner || null;
}

/**
 * Get all files owned by an agent
 */
export function getFilesOwnedBy(agentName) {
  return Object.entries(schemas)
    .filter(([_, info]) => info.owner === agentName)
    .map(([name, info]) => ({
      name,
      location: info.location,
      description: info.description
    }));
}

/**
 * Get all schemas
 */
export function getAllSchemas() {
  return { ...schemas };
}

/**
 * Project folder structure
 */
export const projectStructure = {
  root: [
    'project.json',      // Silas
    'state.json',        // Silas
    'scope.json',        // Nefario
    'requirements.json', // Nefario
    'assumptions.json',  // Shared
    'risks.json',        // Tom
    'gaps.json',         // Lucy
    'README.md'          // Auto-generated by Silas
  ],
  security: [
    'threat-model.json', // Tom
    'permissions.json',  // Tom
    'audit-log.json'     // Tom
  ],
  ops: [
    'environments.json', // Tom
    'deployment.md',     // Tom (optional)
    'runbooks/'          // Tom (optional)
  ],
  quality: [
    'test-coverage.json', // Lucy
    'code-quality.json',  // Lucy
    'metrics.json'        // Lucy
  ],
  architecture: [
    'overview.md',       // Nefario
    'components.json',   // Nefario
    'decisions/'         // Nefario (ADRs)
  ]
};

export default schemas;
